language: java
sudo: true
install: true

dist: trusty

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - develop
    - future-adamov-00-02

before_install:
# - chmod +x mvnw

#before_cache:
#  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    $HOME/.m2/repository
    $HOME/.sonar/cache
    $HOME/.mvn
    .mvn

addons:
  sonarcloud:
    organization: "lolret-github"
    token:
      secure: $SONAR_API_KEY

script:
./mvnw clean install
#    - ./gradlew clean
#    - ./gradlew check
#    - ./gradlew sonarqube build
#  - sonar-scanner
#TODO dont forget stage task for heroku
#deploy:
#  provider: heroku
#  api_key:
#    secure: $HEROKU_API_KEY
#  app: $HEROKU_DEVELOP_APP
#  on:
#    all_branches: true
#  skip_cleanup: true