language: java
sudo: true

install: true
- "mvn -N io.takari:maven:wrapper -Dmaven=4.0.0"
- "./mvnw --show-version --errors --batch-mode test-compile dependency:go-offline"
dist: trusty

before_script:
- psql -c 'create database student_test' -U postgres
- sudo -u postgres psql -c "ALTER ROLE postgres WITH password '123'"

jdk:
- oraclejdk8

branches:
  only:
  - feature-00-02-traviswithsonar

env:
- MAVEN_VERSION=4.0.0

services:
- postgresql

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'

addons:
  postgresql: "9.5"
  sonarcloud:
    organization: "yacommand" # the key of the org you chose at step #3
    token:
      secure: a9df1a57e3b50afd2ebe362fa4196979d905471d # encrypted value of your token
#script:
## other script steps might be done before running the actual analysis
#- mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V
script: ./mvnw clean install

