language: java
sudo: true
install: true
dist: trusty

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master
    - develop

before_install:
 - chmod +x mvnw

cache:
  directories:
    $HOME/.m2
    $HOME/.sonar/cache
    $HOME/.mvn
    .mvn

addons:
  sonarcloud:
    organization: "lolret-github"
    token:
      secure: $SONAR_API_KEY

script:
  ./mvnw clean package sonar:sonar
